version: 2

jobs:

  build-2.7:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Docker image
          command: cp -R files 2.7/files
      - run:
          name: Build Docker image
          command: docker build --no-cache -t lowieh/docker-python-gcp:2.7 2.7
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/docker-python-gcp:2.7
            fi

  build-3.4:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Docker image
          command: cp -R files 3.4/files
      - run:
          name: Build Docker image
          command: docker build --no-cache -t lowieh/docker-python-gcp:3.4 3.4
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/docker-python-gcp:3.4
            fi

  build-3.5:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Docker image
          command: cp -R files 3.5/files
      - run:
          name: Build Docker image
          command: docker build --no-cache -t lowieh/docker-python-gcp:3.5 3.5
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/docker-python-gcp:3.5
            fi

  build-3.6:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Docker image
          command: cp -R files 3.6/files
      - run:
          name: Build Docker image
          command: docker build --no-cache -t lowieh/docker-python-gcp:3.6 3.6
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/docker-python-gcp:3.6
            fi


workflows:
  version: 2

  build:
    jobs:
      - build-2.7
      - build-3.4
      - build-3.5
      - build-3.6
